version: '2'
services:
    reverseproxy:
        image: reverseproxy:latest
        ports:
            - 8080:8080
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: nrstut:1.0
        ports:
            - 8083:8083
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: bulletinboard:1.0
        ports:
            - 8085:8085
        restart: always